/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.zooproject.Vista;

import com.mycompany.zooproject.Controlador.Plans;
import static java.lang.Integer.parseInt;

/**
 *
 * @author USUARIO
 */
public class TicketWindow extends javax.swing.JFrame {

    /**
     * Creates new form TicketWindow
     */
    public TicketWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rbSencillo = new javax.swing.JRadioButton();
        rbPLus = new javax.swing.JRadioButton();
        rbPlusGuiado = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnComprarTicket = new javax.swing.JButton();
        btnIrAZoo = new javax.swing.JButton();
        tfTicketQuantity = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Selecciona el tipo de ticket que deseas comprar: ");

        buttonGroup1.add(rbSencillo);
        rbSencillo.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        rbSencillo.setForeground(new java.awt.Color(51, 51, 51));
        rbSencillo.setText("Sencillo US 5");
        rbSencillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSencilloActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbPLus);
        rbPLus.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        rbPLus.setForeground(new java.awt.Color(51, 51, 51));
        rbPLus.setText("Plus US 7");
        rbPLus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPLusActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbPlusGuiado);
        rbPlusGuiado.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        rbPlusGuiado.setForeground(new java.awt.Color(51, 51, 51));
        rbPlusGuiado.setText("Plus Guiado US 10");
        rbPlusGuiado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPlusGuiadoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Venta de tickets");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Nota: Con el ticket sencillo puedes obtener el ingreso al Zoológico y ver los animales, ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("con el Plus puedes además de ver los animales tienes derecho a un refigerio,");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("y con el Plus Guiado además de los beneficios del plus, tendrás derecho a un recorrido guiado.");

        jLabel7.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Ingrese la cantidad de tickets a comprar:");

        btnComprarTicket.setForeground(new java.awt.Color(51, 51, 51));
        btnComprarTicket.setText("Comprar ticket");
        btnComprarTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarTicketActionPerformed(evt);
            }
        });

        btnIrAZoo.setForeground(new java.awt.Color(51, 51, 51));
        btnIrAZoo.setText("Volver");
        btnIrAZoo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrAZooActionPerformed(evt);
            }
        });

        tfTicketQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTicketQuantityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfTicketQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(457, 457, 457)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbSencillo)
                                    .addComponent(rbPLus)
                                    .addComponent(rbPlusGuiado)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(355, 355, 355)
                                .addComponent(btnIrAZoo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnComprarTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 88, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbSencillo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbPLus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbPlusGuiado)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTicketQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIrAZoo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnComprarTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbPLusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPLusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbPLusActionPerformed

    private void rbPlusGuiadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPlusGuiadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbPlusGuiadoActionPerformed

    private void rbSencilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSencilloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbSencilloActionPerformed

    private void btnIrAZooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrAZooActionPerformed
        // TODO add your handling code here:
        new PlanWindow().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnIrAZooActionPerformed

    private void btnComprarTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarTicketActionPerformed
        // TODO add your handling code here:
         if (rbSencillo.isSelected()){
            ZooWindow.costumers.getCostumer().get(ZooWindow.currentCostumer).setTicketCode("1");
            ZooWindow.costumers.getCostumer().get(ZooWindow.currentCostumer).setPurchaseAmount(Plans.SIMPLE_TICKET_VALUE*parseInt(tfTicketQuantity.getText()));
            System.out.println("Sencillo "+ZooWindow.costumers.getCostumer().get(ZooWindow.currentCostumer).getPurchaseAmount());
        } else if (rbPLus.isSelected()){
            ZooWindow.costumers.getCostumer().get(ZooWindow.currentCostumer).setTicketCode("2");
            ZooWindow.costumers.getCostumer().get(ZooWindow.currentCostumer).setPurchaseAmount(Plans.PLUS_TICKET_VALUE*parseInt(tfTicketQuantity.getText()));
            System.out.println("plus "+ ZooWindow.costumers.getCostumer().get(ZooWindow.currentCostumer).getPurchaseAmount());

        } else if (rbPlusGuiado.isSelected()){
            ZooWindow.costumers.getCostumer().get(ZooWindow.currentCostumer).setTicketCode("3");
            ZooWindow.costumers.getCostumer().get(ZooWindow.currentCostumer).setPurchaseAmount(Plans.PLUS_GUIDED_TICKET_VALUE*parseInt(tfTicketQuantity.getText()));
            System.out.println("plus g" + ZooWindow.costumers.getCostumer().get(ZooWindow.currentCostumer).getPurchaseAmount());

        }
         
        
    }//GEN-LAST:event_btnComprarTicketActionPerformed

    private void tfTicketQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTicketQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTicketQuantityActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprarTicket;
    private javax.swing.JButton btnIrAZoo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbPLus;
    private javax.swing.JRadioButton rbPlusGuiado;
    private javax.swing.JRadioButton rbSencillo;
    private javax.swing.JTextField tfTicketQuantity;
    // End of variables declaration//GEN-END:variables
}
