/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.zooproject.Vista;

import com.itextpdf.text.DocumentException;
import com.mycompany.zooproject.Controlador.Animal;
import com.mycompany.zooproject.Controlador.Costumer;
import com.mycompany.zooproject.Modelo.AnimalManagement;
import com.mycompany.zooproject.Modelo.CostumerManagement;
import java.io.FileNotFoundException;
import static java.lang.Integer.parseInt;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author brayan
 */
public class ZooWindow extends javax.swing.JFrame {
    //Parameters
    public static CostumerManagement costumers = new CostumerManagement();
    public static AnimalManagement animals = new AnimalManagement();
    public static int currentCostumer = -1;

    /**
     * Creates new form ZooWindow
     */
    public ZooWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.ButtonGroup bgMammal = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnGoBuyAnimalFood = new javax.swing.JButton();
        btnGoBuyPeopleFood = new javax.swing.JButton();
        btnGoBuyPet = new javax.swing.JButton();
        btnGoPlan = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfID = new javax.swing.JTextField();
        tfName1 = new javax.swing.JTextField();
        tfAge = new javax.swing.JTextField();
        btnAddCostumer = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tfAnimalCode = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfAnimalName1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfAnimalAge = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfAnimalState = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfAnimalGender1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tfAnimalOrigin = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnAddAnimal = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        tfAnimalHabitat = new javax.swing.JTextField();
        rbMammalYes = new javax.swing.JRadioButton();
        rbMammalNo = new javax.swing.JRadioButton();
        btnGetOut = new javax.swing.JButton();
        btnGeneratePDF1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        jLabel1.setFont(new java.awt.Font("Likhan", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Zoo Patitas Felices");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnGoBuyAnimalFood.setFont(new java.awt.Font("AnjaliOldLipi", 1, 18)); // NOI18N
        btnGoBuyAnimalFood.setForeground(new java.awt.Color(51, 51, 51));
        btnGoBuyAnimalFood.setText("Ir a comprar comida para animal");
        btnGoBuyAnimalFood.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153)));
        btnGoBuyAnimalFood.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGoBuyAnimalFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBuyAnimalFoodActionPerformed(evt);
            }
        });

        btnGoBuyPeopleFood.setFont(new java.awt.Font("AnjaliOldLipi", 1, 18)); // NOI18N
        btnGoBuyPeopleFood.setForeground(new java.awt.Color(51, 51, 51));
        btnGoBuyPeopleFood.setText("Ir a comprar comida para personas");
        btnGoBuyPeopleFood.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153)));
        btnGoBuyPeopleFood.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGoBuyPeopleFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBuyPeopleFoodActionPerformed(evt);
            }
        });

        btnGoBuyPet.setFont(new java.awt.Font("AnjaliOldLipi", 1, 18)); // NOI18N
        btnGoBuyPet.setForeground(new java.awt.Color(51, 51, 51));
        btnGoBuyPet.setText("Ir a comprar mascota");
        btnGoBuyPet.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153)));
        btnGoBuyPet.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGoBuyPet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoBuyPetActionPerformed(evt);
            }
        });

        btnGoPlan.setFont(new java.awt.Font("AnjaliOldLipi", 1, 18)); // NOI18N
        btnGoPlan.setForeground(new java.awt.Color(51, 51, 51));
        btnGoPlan.setText("Ir a planes");
        btnGoPlan.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153)));
        btnGoPlan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGoPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoPlanActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Administración", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Liberation Mono", 2, 18))); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cliente", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Liberation Mono", 2, 15))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Liberation Mono", 1, 15)); // NOI18N
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Liberation Mono", 1, 15)); // NOI18N
        jLabel3.setText("Documento ");

        jLabel4.setFont(new java.awt.Font("Liberation Mono", 1, 15)); // NOI18N
        jLabel4.setText("Edad");

        tfID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIDActionPerformed(evt);
            }
        });

        tfName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfName1ActionPerformed(evt);
            }
        });

        tfAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAgeActionPerformed(evt);
            }
        });

        btnAddCostumer.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnAddCostumer.setText("Agregar cliente");
        btnAddCostumer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCostumerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfName1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddCostumer)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfAge, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(btnAddCostumer)
                .addGap(31, 31, 31))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Animal", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Liberation Mono", 2, 15))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Liberation Mono", 1, 15)); // NOI18N
        jLabel5.setText("Nombre");

        tfAnimalCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAnimalCodeActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Liberation Mono", 1, 15)); // NOI18N
        jLabel6.setText("Código");

        tfAnimalName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAnimalName1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Liberation Mono", 1, 15)); // NOI18N
        jLabel7.setText("Edad");

        tfAnimalAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAnimalAgeActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Liberation Mono", 1, 15)); // NOI18N
        jLabel8.setText("Origen");

        tfAnimalState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAnimalStateActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Liberation Mono", 1, 15)); // NOI18N
        jLabel9.setText("Género");

        tfAnimalGender1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAnimalGender1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Liberation Mono", 1, 15)); // NOI18N
        jLabel10.setText("Estado");

        tfAnimalOrigin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAnimalOriginActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Liberation Mono", 1, 15)); // NOI18N
        jLabel11.setText("Mamífero");

        btnAddAnimal.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnAddAnimal.setText("Agregar animal");
        btnAddAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAnimalActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Liberation Mono", 1, 15)); // NOI18N
        jLabel12.setText("Hábitat");

        tfAnimalHabitat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAnimalHabitatActionPerformed(evt);
            }
        });

        bgMammal.add(rbMammalYes);
        rbMammalYes.setText("Sí");
        rbMammalYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMammalYesActionPerformed(evt);
            }
        });

        bgMammal.add(rbMammalNo);
        rbMammalNo.setText("No");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfAnimalHabitat, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfAnimalGender1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfAnimalState, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfAnimalAge, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfAnimalName1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfAnimalCode, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfAnimalOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddAnimal)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(rbMammalYes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbMammalNo)))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfAnimalName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfAnimalCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfAnimalAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfAnimalGender1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfAnimalState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfAnimalOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(rbMammalYes)
                    .addComponent(rbMammalNo))
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tfAnimalHabitat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(btnAddAnimal)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnGetOut.setFont(new java.awt.Font("AnjaliOldLipi", 1, 18)); // NOI18N
        btnGetOut.setForeground(new java.awt.Color(51, 51, 51));
        btnGetOut.setText("Salir");
        btnGetOut.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153)));
        btnGetOut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGetOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetOutActionPerformed(evt);
            }
        });

        btnGeneratePDF1.setFont(new java.awt.Font("AnjaliOldLipi", 1, 18)); // NOI18N
        btnGeneratePDF1.setForeground(new java.awt.Color(51, 51, 51));
        btnGeneratePDF1.setText("Cerrar Caja + Factura");
        btnGeneratePDF1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153)));
        btnGeneratePDF1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGeneratePDF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneratePDF1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 311, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnGoBuyAnimalFood, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnGoPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnGoBuyPet, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnGoBuyPeopleFood, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnGeneratePDF1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnGetOut, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(292, 292, 292))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGoPlan, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGoBuyPet, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGoBuyAnimalFood, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGoBuyPeopleFood, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGetOut, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGeneratePDF1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGoBuyAnimalFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBuyAnimalFoodActionPerformed
        // TODO add your handling code here:
        new BuyFoodAnimalWindow().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnGoBuyAnimalFoodActionPerformed

    private void btnGoBuyPeopleFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBuyPeopleFoodActionPerformed
        // TODO add your handling code here:
        new BuyCostumerFoodWindow().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnGoBuyPeopleFoodActionPerformed

    private void btnGoBuyPetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoBuyPetActionPerformed
        // TODO add your handling code here:
        new BuyPetWindow().setVisible(true);
        dispose();
        
    }//GEN-LAST:event_btnGoBuyPetActionPerformed

    private void btnGoPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoPlanActionPerformed
        // TODO add your handling code here:
        //new ZooWindow().setVisible(false);
        //System.exit(0);
        new PlanWindow().setVisible(true);
        dispose();
 
    }//GEN-LAST:event_btnGoPlanActionPerformed

    private void tfIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIDActionPerformed

    private void tfName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfName1ActionPerformed

    private void tfAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAgeActionPerformed

    private void tfAnimalCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAnimalCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAnimalCodeActionPerformed

    private void tfAnimalName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAnimalName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAnimalName1ActionPerformed

    private void tfAnimalAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAnimalAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAnimalAgeActionPerformed

    private void tfAnimalStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAnimalStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAnimalStateActionPerformed

    private void tfAnimalGender1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAnimalGender1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAnimalGender1ActionPerformed

    private void tfAnimalOriginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAnimalOriginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAnimalOriginActionPerformed

    private void tfAnimalHabitatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAnimalHabitatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAnimalHabitatActionPerformed

    private void btnGetOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetOutActionPerformed
        //Printing all the costumers in the console
        System.out.println("COSTUMERS");
        for (Costumer c : costumers.getCostumer()){
            System.out.println(
                    "name : " + c.getName()+ "\n" +
                    "Age: " + c.getAge() + "\n" +
                    "Plan: "+ c.getPlan() + "\n");
        }
        
        //Printing all the animals in the console
        System.out.println("\n"+"ANIMALS");
        for(Animal a:animals.getAnimal()){
            System.out.println(
                    a.getName() + " " 
                  + a.getCode() + " " 
                  + a.getAge() + " " 
                  + a.getGender() + " "
                  + a.getState() + " "
                  + a.getOrigin() + " "
                  + a.getMammal() + " "
                  + a.getHabitat() + "\n"
            );
        }

        dispose();
    }//GEN-LAST:event_btnGetOutActionPerformed

    private void btnGeneratePDF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneratePDF1ActionPerformed
        // TODO add your handling code here:
        GeneratePDF pdfFile = new GeneratePDF();
        try {
            pdfFile.generatePDF();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ZooWindow.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(ZooWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGeneratePDF1ActionPerformed

    private void btnAddCostumerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCostumerActionPerformed
        // TODO add your handling code here:
        Costumer costumer = new Costumer(
                tfName1.getText(), 
                tfID.getText(), 
                parseInt(tfAge.getText()));
        
        costumers.addCostumer(costumer);
        currentCostumer += 1;
        System.out.println(costumer.getName() + " " + costumer.getAge() + " " + costumer.getId());
        
        //Cleaning fields
        tfName1.setText(""); 
        tfID.setText(""); 
        tfAge.setText("");
    }//GEN-LAST:event_btnAddCostumerActionPerformed

    private void rbMammalYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMammalYesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbMammalYesActionPerformed

    private void btnAddAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAnimalActionPerformed
        // TODO add your handling code here:
        boolean mammal = false;
        if(rbMammalYes.isSelected()){
            mammal = true;
        } 
        Animal animal = new Animal(
                tfAnimalName1.getText(), 
                tfAnimalCode.getText(), 
                parseInt(tfAnimalAge.getText()),
                tfAnimalGender1.getText(),
                tfAnimalState.getText(),
                tfAnimalOrigin.getText(),
                mammal,
                tfAnimalHabitat.getText());
        
        animals.addAnimal(animal);
        
        //Cleaning fields
        tfAnimalName1.setText("");
        tfAnimalCode.setText("");
        tfAnimalAge.setText("");
        tfAnimalGender1.setText("");
        tfAnimalState.setText("");
        tfAnimalOrigin.setText("");
        tfAnimalHabitat.setText("");
        rbMammalNo.setSelected(false);
        rbMammalYes.setSelected(false);
    }//GEN-LAST:event_btnAddAnimalActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAnimal;
    private javax.swing.JButton btnAddCostumer;
    private javax.swing.JButton btnGeneratePDF1;
    private javax.swing.JButton btnGetOut;
    private javax.swing.JButton btnGoBuyAnimalFood;
    private javax.swing.JButton btnGoBuyPeopleFood;
    private javax.swing.JButton btnGoBuyPet;
    private javax.swing.JButton btnGoPlan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton rbMammalNo;
    private javax.swing.JRadioButton rbMammalYes;
    private javax.swing.JTextField tfAge;
    private javax.swing.JTextField tfAnimalAge;
    private javax.swing.JTextField tfAnimalCode;
    private javax.swing.JTextField tfAnimalGender1;
    private javax.swing.JTextField tfAnimalHabitat;
    private javax.swing.JTextField tfAnimalName1;
    private javax.swing.JTextField tfAnimalOrigin;
    private javax.swing.JTextField tfAnimalState;
    private javax.swing.JTextField tfID;
    private javax.swing.JTextField tfName1;
    // End of variables declaration//GEN-END:variables
}
